=== FabianNorbertoEscobar/XML-XSLT-XQuery-ejercicios/personas.dtd
<!ELEMENT personas (persona)*>
<!ELEMENT persona (nombre,apellido,fechaNac,genero,tel?,cel?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT fechaNac (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT cel (#PCDATA)>

=== FabianNorbertoEscobar/XML-XSLT-XQuery-ejercicios/personas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE personas SYSTEM "personas.dtd">

<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personas.xsd">

	<persona>
		<nombre>Diego</nombre>
		<apellido>Nuñez</apellido>
		<fechaNac>21/01/2001</fechaNac>
		<genero>Masculino</genero>
	</persona>

	<persona>
		<nombre>Ana</nombre>
		<apellido>Díaz</apellido>
		<fechaNac>01/02/1998</fechaNac>
		<genero>Femenino</genero>
		<tel>011-3535-5353</tel>
	</persona>

	<persona>
		<nombre>Pablo</nombre>
		<apellido>Perez</apellido>
		<fechaNac>05/08/1957</fechaNac>
		<genero>Masculino</genero>
		<tel>011-4242-2424</tel>
		<cel>011-15-9876-5432</cel>
	</persona>


</personas>
