<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE videoclub [
	<!ELEMENT Videoclub (Pelicula | Documental)*>
	<!ELEMENT Pelicula (Titulo, Actores, Nota?)>
	<!ATTLIST Pelicula id CDATA #REQUIRED Precio CDATA #REQUIRED>
	<!ELEMENT Documental (Titulo)>
	<!ATTLIST Documental mes CDATA #REQUIRED anio CDATA #REQUIRED>
	<!ELEMENT Titulo (#PCDATA)>
	<!ELEMENT Actores (Actor+)>
	<!ELEMENT Nota (#PCDATA)>
	<!ELEMENT Actor (Nombre, Apellido)>
	<!ELEMENT Nombre (#PCDATA)>
	<!ELEMENT Apellido (#PCDATA)>
]>

<Videoclub>

	<Pelicula id="tt0372784" Precio="85" >
		<Titulo>Batman inicia</Titulo>
		<Actores>
			<Actor>
				<Nombre>Christian</Nombre>
				<Apellido>Bale</Apellido>
			</Actor>
			<Actor>
				<Nombre>Michael</Nombre>
				<Apellido>Cane</Apellido>
			</Actor>
		</Actores>
	</Pelicula>

	<Pelicula id="tt0892255" Precio="100">
		<Title>Che - El argumento</Title>
		<Actores>
			<Actor>
				<Nombre>Julia</Nombre>
				<Apellido>Ormond</Apellido>
			</Actor>
			<Actor>
				<Nombre>Benicio</Nombre>
				<Apellido>Del Toro</Apellido>
			</Actor>
			<Actor>
				<Nombre>Oscar</Nombre>
				<Apellido>Isaac</Apellido>
			</Actor>
		</Actores>
		<Nota>
			Vea esta pelicula y además la segunda parte
		</Nota>
	</Pelicula>

	<Documental mes="enero" anio="2005">
		<Titulo>La marcha de los pingüinos</Titulo>
	</Documental>

</Videoclub>
